# -*- coding: utf-8 -*-
"""Day-8-Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqVwd0Vaf9oiF_eqzW5vAuTx3HKLeQhT

# Traffic-Sign-Localization-Detection-YOLO-Annotated
[Dataset](https://www.kaggle.com/datasets/ahemateja19bec1025/trafficsignlocalizationdetectionyoloannotated)
"""

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("ahemateja19bec1025/trafficsignlocalizationdetectionyoloannotated")

print("Path to dataset files:", path)
print(os.listdir(path))

to_train_path = path

"""# Task
Generate YOLO training using the folder structure "/kaggle/input/traffic-signs-dataset-in-yolo-format/train/images", "/kaggle/input/traffic-signs-dataset-in-yolo-format/train/labels", "/kaggle/input/traffic-signs-dataset-in-yolo-format/test/images", and "/kaggle/input/traffic-signs-dataset-in-yolo-format/test/labels" with `ultralytics`.

## Install ultralytics

### Subtask:
Install the `ultralytics` library.

**Reasoning**:
The subtask is to install the `ultralytics` library. This can be done using pip in a code cell.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics

"""## Create data.yaml

### Subtask:
Create a `data.yaml` file that specifies the paths to your training and validation image and label directories, the number of classes, and the class names.

**Reasoning**:
Create the data_yaml_dict, import the yaml library, and write the data_yaml_dict to a file named data.yaml.
"""

import yaml

data_yaml_dict = {
    'train': '/kaggle/input/traffic-signs-dataset-in-yolo-format/train/images',
    'val': '/kaggle/input/traffic-signs-dataset-in-yolo-format/test/images',
    'nc': 4,
    'names': ['prohibitory', 'danger', 'mandatory', 'other']
}

with open('data.yaml', 'w') as f:
    yaml.dump(data_yaml_dict, f)

import os

with open('data.yaml', 'r') as f:
    data_yaml_dict = yaml.safe_load(f)

print(data_yaml_dict)
print(os.listdir())
print(os.curdir)

"""## Load a yolo model

### Subtask:
Load a pre-trained YOLO model using the `ultralytics` library.

**Reasoning**:
Load a pre-trained YOLO model using the `ultralytics` library by importing the `YOLO` class and instantiating a model.
"""

from ultralytics import YOLO

model = YOLO("yolo12n.pt")

import yaml
import os

data = {
    'names': [
        'Cycle Zone',
        'Danger Ahead',
        'Deer Zone',
        'End of Right Road -Go straight-',
        'Give Way',
        'Go Left or Straight',
        'Go Right or Straight',
        'Go Straight',
        'Huddle Road',
        'Left Curve Ahead',
        'Left Sharp Curve',
        'No Entry',
        'No Over Taking Trucks',
        'No Over Taking',
        'No Stopping',
        'No Waiting',
        'Pedestrian',
        'Right Curve Ahead',
        'Right Sharp Curve',
        'Road Work',
        'RoundAbout',
        'Slippery Road',
        'Snow Warning Sign',
        'Speed Limit 100',
        'Speed Limit 120',
        'Speed Limit 20',
        'Speed Limit 30',
        'Speed Limit 50',
        'Speed Limit 60',
        'Speed Limit 70',
        'Speed Limit 80',
        'Stop',
        'Traffic Signals Ahead',
        'Truck Sign',
        'Turn Left',
        'Turn Right'
    ],
    'nc': 36,
    'train': os.path.join(to_train_path,'TrafficSignLocalizationandDetection/train/images'),
    'val': os.path.join(to_train_path,'TrafficSignLocalizationandDetection/valid/images')
}

# Define the filename for the YAML file
yaml_filename = 'traffic_signs_dataset.yaml'

try:
    with open(yaml_filename, 'w') as file:
        yaml.dump(data, file, default_flow_style=False, sort_keys=False)
    print(f"Successfully created '{yaml_filename}' with the provided data.")

    # Optional: Read and print the content to verify
    print(f"\nContent of '{yaml_filename}':")
    with open(yaml_filename, 'r') as file:
        print(file.read())

except Exception as e:
    print(f"An error occurred: {e}")

# Clean up the created file (optional, for demonstration purposes)
# if os.path.exists(yaml_filename):
#     os.remove(yaml_filename)
#     print(f"\nCleaned up: '{yaml_filename}'")

"""## Train the model

### Subtask:
Start the training process using the loaded model and the `data.yaml` file.

**Reasoning**:
Start the training process using the loaded model and the data.yaml file.
"""

to_train_data_path = 'traffic_signs_dataset.yaml'
model.train(data=to_train_data_path, epochs=10, imgsz=640, batch=16)

"""**Reasoning**:
The training failed because the validation image path specified in data.yaml was not found. The error message indicates that the path '/kaggle/input/traffic-signs-dataset-in-yolo-format/test/images' is missing. I need to check the file structure and correct the path in the data.yaml file to the correct location of the test images. The previous cell output showed the path to the dataset files is '/kaggle/input/traffic-signs-dataset-in-yolo-format'. Based on the dataset name "traffic-signs-dataset-in-yolo-format", the test images are likely located at '/kaggle/input/traffic-signs-dataset-in-yolo-format/valid/images'. I will update the 'val' path in data_yaml_dict and rewrite the data.yaml file. Then I will retry the training command.

## Evaluate the model (optional)

### Subtask:
Evaluate the trained model on the test set.

**Reasoning**:
Evaluate the trained model on the test set using the `evaluate()` method.
"""

metrics = model.benchmark(data=to_train_data_path)
print(metrics)

"""## Make predictions (optional)

### Subtask:
Use the trained model to make predictions on new images.

**Reasoning**:
Import the YOLO class, load the pre-trained yolov8n.pt model, make a prediction on an example image from the test set, and print the results.
"""

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

# Load the pre-trained yolov8n.pt model
# model = YOLO('yolo12n.pt')

# Define the path to the image for prediction
# image_path = os.path.join(to_train_path,'TrafficSignLocalizationandDetection/test/images/000539_jpg.rf.53a4e59b7b1c463d526fd835afa67135.jpg')
# image_path = os.path.join(to_train_path,'TrafficSignLocalizationandDetection/train/images/000100_jpg.rf.551371afbaccc11ec1b5faeb2bf3b52c.jpg')
# image_path = os.path.join(to_train_path,'TrafficSignLocalizationandDetection/test/images/000923_JPG.rf.25884ee05b10a072c952102bfeb64967.jpg')
image_path = os.path.join(to_train_path,'TrafficSignLocalizationandDetection/test/images/000943_JPG.rf.6e6e26139431d6b99a55847e3a05fd02.jpg')

# Make predictions on the image
results = model.predict(image_path)

# Load the image using OpenCV
img = cv2.imread(image_path)

# Iterate through the prediction results and draw bounding boxes
for r in results:
    # Check if there are any bounding boxes in the result
    if r.boxes is not None and len(r.boxes) > 0:
        for box in r.boxes:
            # Get the coordinates of the bounding box
            x1, y1, x2, y2 = [int(coord) for coord in box.xyxy[0]]

            # Draw the bounding box on the image
            color = (0, 255, 0)  # Green color for the bounding box
            thickness = 2
            cv2.rectangle(img, (x1, y1), (x2, y2), color, thickness)

            # Optionally, get the class and confidence and display them
            if box.cls is not None and box.conf is not None:
                class_id = int(box.cls[0])
                confidence = float(box.conf[0])
                class_name = model.names[class_id] # Get class name from model

                label = f"{class_name}: {confidence:.2f}"
                font = cv2.FONT_HERSHEY_SIMPLEX
                font_scale = 0.5
                font_thickness = 1
                text_size = cv2.getTextSize(label, font, font_scale, font_thickness)[0]
                text_x = x1
                text_y = y1 - 10 if y1 > 20 else y1 + text_size[1] + 10
                cv2.putText(img, label, (text_x, text_y), font, font_scale, color, font_thickness)


# Display the image with bounding boxes using cv2_imshow
cv2_imshow(img)