# -*- coding: utf-8 -*-
"""Day 8 - assignment - 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TH81FzMe2dsUaG-rYTIbHHh5QP_QUgAv
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("snehilsanyal/construction-site-safety-image-dataset-roboflow")

print("Path to dataset files:", path)



data_yaml_content = """
path: /root/.cache/kagglehub/datasets/snehilsanyal/construction-site-safety-image-dataset-roboflow/versions/3/css-data  # dataset root dir
train: train/images  # train images (relative to 'path') 128 images
val: valid/images  # val images (relative to 'path') 128 images
test: test/images  # test images (relative to 'path') 128 images

# Classes
nc: 10  # number of classes
names: ['Hardhat', 'Mask', 'NO-Hardhat', 'NO-Mask', 'NO-Safety Vest', 'Person', 'Safety Cone', 'Safety Vest', 'machinery', 'vehicle']  # class names
"""

file_path = '/root/.cache/kagglehub/datasets/snehilsanyal/construction-site-safety-image-dataset-roboflow/versions/3/data.yaml'

with open(file_path, 'w') as f:
    f.write(data_yaml_content)

print("data.yaml created successfully!")

# Read and print the content of the file
with open(file_path, 'r') as f:
    file_content = f.read()

print("\nContent of data.yaml:")
print(file_content)

!pip install ultralytics

from ultralytics import YOLO

# Load a model
# You can choose a different model like 'yolov5s.pt', 'yolov8n.pt', etc.
model = YOLO('yolo12n.pt')

# Train the model
# Adjust epochs, img_size, and data path as needed
results = model.train(data='/root/.cache/kagglehub/datasets/snehilsanyal/construction-site-safety-image-dataset-roboflow/versions/3/data.yaml', epochs=10, imgsz=640)

# Predict on an image
# Replace 'path/to/your/image.jpg' with the actual path to your image
# You can also predict on a directory of images or a video
from PIL import Image
results = model.predict('/root/.cache/kagglehub/datasets/snehilsanyal/construction-site-safety-image-dataset-roboflow/versions/3/css-data/test/images/2008_008320_jpg.rf.bd34011d46f82f9410d95f00e560b8ea.jpg')

# Show the image with bounding boxes
for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    display(im)